//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class quotation_autocomplete
    {
        public int id { get; set; }
        public string type { get; set; }
        public string category { get; set; }
        public string label1 { get; set; }
        public Nullable<decimal> unitprice1 { get; set; }
        public string unit1 { get; set; }
        public string label2 { get; set; }
        public Nullable<decimal> unitprice2 { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modify_by { get; set; }
        public string is_deleted { get; set; }
    }
}
